### ISSUE TITLE
Send Email from Contatti Page

### ISSUE THREAD

**Issue by ManuelVargas1251** [sazdg/linoleumPortfolio#1]
## Send Email from a Static HTML

I found some solutions, generally you would need a server but there are some free services we can use.

https://formspree.io/

**Comment by ManuelVargas1251** [comment]
using formspree.io, we can edit the contact form to your custom fields. and their code already has the info to send the email through their service.

https://formspree.io/library/simple-contact-form/

**Comment by sazdg** [comment]
What about form action="mailto:...." easy peasy 
![image](https://user-images.githubusercontent.com/78870726/108895578-0cbbf480-7614-11eb-8127-fc04bc9270df.png)


or maybe better email with php

![image](https://user-images.githubusercontent.com/78870726/108895638-22c9b500-7614-11eb-80e3-bbdc63c11848.png)


https://html.form.guide/email-form/html-email-form/

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108895965-92d83b00-7614-11eb-904c-d6df07f5b4b8.png)

from your suggestion

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108896181-dcc12100-7614-11eb-9a18-44d63b902d41.png)

basically all I need is that action code

**Comment by ManuelVargas1251** [comment]
For the first option you mention, **mailto** will open gmail and you will have to write your own email; there is no automation. Only opens mail client (gmail/outlook/any).

For the second option, we need a php server to run those requests which we currently do not have. unless we have server, we cannot use php :/

**Comment by ManuelVargas1251** [comment]
okay, I am creating an account on formspree to begin testing!

**Comment by sazdg** [comment]
how fast lol
I like your idea but I will try by myself php just to review some php code

**Comment by sazdg** [comment]
> okay, I am creating an account on formspree to begin testing!

![image](https://user-images.githubusercontent.com/78870726/108897257-30803a00-7616-11eb-8cc9-562b3fe299b0.png)

here's the catch :(

**Comment by ManuelVargas1251** [comment]
yes there is a catch, custom forms require you to update also.

alternative site but similar situation:
https://formkeep.com/#pricing

![image](https://user-images.githubusercontent.com/10030407/108897632-f003ca80-75db-11eb-80c7-d6dbf47feade.png)

**Comment by ManuelVargas1251** [comment]
ok I was able to test locally.

![image](https://user-images.githubusercontent.com/10030407/108898144-77e9d480-75dc-11eb-929b-fc8988521239.png)

and I received the email:

![image](https://user-images.githubusercontent.com/10030407/108898199-89cb7780-75dc-11eb-9e91-0fece634d0d3.png)

**Comment by ManuelVargas1251** [comment]
the code I used is below:

```html
     <form action="https://formspree.io/f/mknpadkz" method="POST">
      <input type="text" name="name">
      <input type="email" name="_replyto">
      <input type="submit" value="Send">
    </form>
```

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108898300-56f2a500-7617-11eb-9817-42af79146a15.png)

At least I can write the code but it will never works on github.  And I can add a button "mailto:ecc...."

**Comment by ManuelVargas1251** [comment]
In order to do the PHP site, we would need to also host the files in the php server by deploying in github.
Using heroku is easy as it has integration for github but this will take more time to develop.

https://devcenter.heroku.com/articles/getting-started-with-php
https://devcenter.heroku.com/articles/deploying-php

**Comment by sazdg** [comment]
I understand, that's interesting

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108916227-3da92300-762e-11eb-9322-06c1167c81be.png)

**Comment by sazdg** [comment]
ah lol I can see it

**Comment by ManuelVargas1251** [comment]
yes, click in the Source section, and select my branch. it is named, contact-form-update-mv

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108916665-df307480-762e-11eb-8252-ac5f3fbb5749.png)

**Comment by sazdg** [comment]
I don't see any difference, do you?

**Comment by ManuelVargas1251** [comment]
I do! just tried it, check your email.

![image](https://user-images.githubusercontent.com/10030407/108916872-7debaf80-75f4-11eb-9a31-1274edf3f224.png)

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108916946-4817ec80-762f-11eb-9786-863fad5cd488.png)

yessss!!!!

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108917047-6c73c900-762f-11eb-9f74-b61c2d47be57.png)

Is this a real email? ahhaha

**Comment by ManuelVargas1251** [comment]
yes, I own mmvv.pw and I have a catch all rule for any email address.
so I can make up a name and I get it delivered.
prettyweirdhuh@mmvv.pw

**Comment by sazdg** [comment]
Thank you so much Manolo!1!!1!11 Tu eres genial

**Comment by ManuelVargas1251** [comment]
if you click on my email link above, that is the **mailto** function. FYI

![image](https://user-images.githubusercontent.com/10030407/108917259-15510280-75f5-11eb-9a2e-7724ecf19d48.png)

**Comment by sazdg** [comment]
yay I tried, I don't like it

**Comment by ManuelVargas1251** [comment]
Please click on **pull request** in your repo front page (bottom right) :

![image](https://user-images.githubusercontent.com/10030407/108917516-7aa4f380-75f5-11eb-9ef9-43f42428b7c3.png)

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108917761-89f56280-7630-11eb-9386-c96a66abf6b0.png)

**Comment by ManuelVargas1251** [comment]
no, make sure the base is your master(main) branch

**Comment by sazdg** [comment]
![image](https://user-images.githubusercontent.com/78870726/108917844-aee9d580-7630-11eb-9d8c-db37b70633f3.png)

I think this is correct

**Comment by ManuelVargas1251** [comment]
yes!

**Comment by ManuelVargas1251** [comment]
Pull Request to merge to master branch:
https://github.com/sazdg/linoleumPortfolio/pull/2
